services:
  app-template:
    container_name: ${APP_NAME}-${APP_PROFILE}
    build:
      context: .
      dockerfile: Dockerfile
    image: project-base/${APP_NAME}:${APP_VERSION:-latest}
    restart: unless-stopped
    environment:
      - "SPRING_PROFILES_ACTIVE=${APP_PROFILE}"
    ports:
      - "${APP_PORT}:8080"
    networks:
      - app-network
      - observability
      - data

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME}-${APP_PROFILE}
  observability:
    external: true
  data:
    external: true