services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: data-postgres
    hostname: postgres
    restart: unless-stopped
    user: 999:999
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
