version: "3.5"

networks:
  default:
    driver: bridge
    name: app-template
  observability:
    external: true
  data:
    external: true
services:
  app-template:
    container_name: app-template
    image: project-base/app-template:latest
    restart: unless-stopped
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - "8080"
    networks:
      - observability
      - data