services:
  otel-collector:
    image: otel/opentelemetry-collector:${OTEL_VERSION}
    container_name: observability-otel
    hostname: otel-collector
    restart: unless-stopped
    user: "0"
    volumes:
      - ./conf:/etc/otelcol
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889"
    depends_on:
      - data-prepper
      - jaeger-tracing
