services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: data-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
