services:
  cloudflared:
    image: cloudflare/cloudflared:${CLOUDFLARED_VERSION}
    container_name: networking-cloudflared
    hostname: cloudflared
    restart: unless-stopped
    entrypoint: "cloudflared"
    volumes:
      - ./conf.yml:/etc/cloudflared/conf.yml
      - ./:/root/.cloudflared
    networks:
      - networking
